<option value="*">*</option>
<option value="**">**</option>
<option value="**D">**Distinction</option>
<option value="*A">*A</option>
<option value="*B">*B</option>
<option value="*C">*C</option>
<option value="*D">*D</option>
<option value="*DD">*DD</option>
<option value="*E">*E</option>
<option value="*F">*F</option>
<option value="*G">*G</option>
<option value="A">A</option>
<option value="A*">A*</option>
<option value="A*A">A*A</option>
<option value="A*A*">A*A*</option>
<option value="AA">AA</option>
<option value="AA*">AA*</option>
<option value="AAA">AAA</option>
<option value="AAB">AAB</option>
<option value="AAC">AAC</option>
<option value="AAD">AAD</option>
<option value="AAE">AAE</option>
<option value="AB">AB</option>
<option value="ABA">ABA</option>
<option value="ABB">ABB</option>
<option value="ABC">ABC</option>
<option value="ABD">ABD</option>
<option value="ABE">ABE</option>
<option value="AC">AC</option>
<option value="ACA">ACA</option>
<option value="ACB">ACB</option>
<option value="ACC">ACC</option>
<option value="ACD">ACD</option>
<option value="ACE">ACE</option>
<option value="EL1">achievement at entry level 1</option>
<option value="EL2">achievement at entry level 2</option>
<option value="EL3">achievement at entry level 3</option>
<option value="AD">AD</option>
<option value="ADA">ADA</option>
<option value="ADB">ADB</option>
<option value="ADC">ADC</option>
<option value="ADD">ADD</option>
<option value="ADE">ADE</option>
<option value="AE">AE</option>
<option value="AEA">AEA</option>
<option value="AEB">AEB</option>
<option value="AEC">AEC</option>
<option value="AED">AED</option>
<option value="AEE">AEE</option>
<option value="AF">AF</option>
<option value="AG">AG</option>
<option value="B">B</option>
<option value="B*">B*</option>
<option value="BA">BA</option>
<option value="BAA">BAA</option>
<option value="BAB">BAB</option>
<option value="BAC">BAC</option>
<option value="BAD">BAD</option>
<option value="BAE">BAE</option>
<option value="BB">Bb</option>
<option value="BBA">BBA</option>
<option value="BBB">BBB</option>
<option value="BBC">BBC</option>
<option value="BBD">BBD</option>
<option value="BBE">BBE</option>
<option value="BC">BC</option>
<option value="BCA">BCA</option>
<option value="BCB">BCB</option>
<option value="BCC">BCC</option>
<option value="BCD">BCD</option>
<option value="BCE">BCE</option>
<option value="BD">BD</option>
<option value="BDA">BDA</option>
<option value="BDB">BDB</option>
<option value="BDC">BDC</option>
<option value="BDD">BDD</option>
<option value="BDE">BDE</option>
<option value="BE">BE</option>
<option value="BEA">BEA</option>
<option value="BEB">BEB</option>
<option value="BEC">BEC</option>
<option value="BED">BED</option>
<option value="BEE">BEE</option>
<option value="BF">BF</option>
<option value="BG">BG</option>
<option value="C">C</option>
<option value="C*">C*</option>
<option value="CA">CA</option>
<option value="CAA">CAA</option>
<option value="CAB">CAB</option>
<option value="CAC">CAC</option>
<option value="CAD">CAD</option>
<option value="CAE">CAE</option>
<option value="CB">CB</option>
<option value="CBA">CBA</option>
<option value="CBB">CBB</option>
<option value="CBC">CBC</option>
<option value="CBD">CBD</option>
<option value="CBE">CBE</option>
<option value="CC">CC</option>
<option value="CCA">CCA</option>
<option value="CCB">CCB</option>
<option value="CCC">CCC</option>
<option value="CCD">CCD</option>
<option value="CCE">CCE</option>
<option value="CD">CD</option>
<option value="CDA">CDA</option>
<option value="CDB">CDB</option>
<option value="CDC">CDC</option>
<option value="CDD">CDD</option>
<option value="CDE">CDE</option>
<option value="CE">CE</option>
<option value="CEA">CEA</option>
<option value="CEB">CEB</option>
<option value="CEC">CEC</option>
<option value="CED">CED</option>
<option value="CEE">CEE</option>
<option value="CF">CF</option>
<option value="CG">CG</option>
<option value="CR">Credit</option>
<option value="D">D</option>
<option value="D*">D*</option>
<option value="D1">D1</option>
<option value="D2">D2</option>
<option value="D3">D3</option>
<option value="DA">DA</option>
<option value="DAA">DAA</option>
<option value="DAB">DAB</option>
<option value="DAC">DAC</option>
<option value="DAD">DAD</option>
<option value="DAE">DAE</option>
<option value="DB">DB</option>
<option value="DBA">DBA</option>
<option value="DBB">DBB</option>
<option value="DBC">DBC</option>
<option value="DBD">DBD</option>
<option value="DBE">DBE</option>
<option value="DC">DC</option>
<option value="DCA">DCA</option>
<option value="DCB">DCB</option>
<option value="DCC">DCC</option>
<option value="DCD">DCD</option>
<option value="DCE">DCE</option>
<option value="DD">DD</option>
<option value="DDA">DDA</option>
<option value="DDB">DDB</option>
<option value="DDC">DDC</option>
<option value="DDDD">DDDD</option>
<option value="DDDM">DDDM</option>
<option value="DDDP">DDDP</option>
<option value="DDE">DDE</option>
<option value="DDMD">DDMD</option>
<option value="DDMM">DDMM</option>
<option value="DDMP">DDMP</option>
<option value="DDPD">DDPD</option>
<option value="DDPM">DDPM</option>
<option value="DDPP">DDPP</option>
<option value="DE">DE</option>
<option value="DEA">DEA</option>
<option value="DEB">DEB</option>
<option value="DEC">DEC</option>
<option value="DED">DED</option>
<option value="DEE">DEE</option>
<option value="DF">DF</option>
<option value="DG">DG</option>
<option value="E3">DIAGNOSTIC ENTRY 3</option>
<option value="LN">DIAGNOSTIC LEVEL 2 (NO NEED)</option>
<option value="L1">DIAGNOSTIC NEED AT LEVEL 1</option>
<option value="L2">DIAGNOSTIC NEED AT LEVEL 2</option>
<option value="D*D*D">Disinction* Distinction* Distinction</option>
<option value="DS">Distinction</option>
<option value="DS*">Distinction *</option>
<option value="DDD">DISTINCTION DISTINCTION DISTINCTION</option>
<option value="DDM">DISTINCTION DISTINCTION MERIT</option>
<option value="DDP">DISTINCTION DISTINCTION PASS</option>
<option value="DM">DISTINCTION MERIT</option>
<option value="DMM">DISTINCTION MERIT MERIT</option>
<option value="DMP">DISTINCTION MERIT PASS</option>
<option value="DP">DISTINCTION PASS</option>
<option value="DPP">DISTINCTION PASS PASS</option>
<option value="D*D">Distinction* Distinction</option>
<option value="D*DD">Distinction* Distinction Distinction</option>
<option value="D*D*">Distinction* Distinction*</option>
<option value="D*D*D*">Distinction* Distinction* Distinction*</option>
<option value="DMD">DMD</option>
<option value="DMDD">DMDD</option>
<option value="DMDM">DMDM</option>
<option value="DMDP">DMDP</option>
<option value="DMMD">DMMD</option>
<option value="DMMM">DMMM</option>
<option value="DMMP">DMMP</option>
<option value="DMPD">DMPD</option>
<option value="DMPM">DMPM</option>
<option value="DMPP">DMPP</option>
<option value="DPD">DPD</option>
<option value="DPDD">DPDD</option>
<option value="DPDM">DPDM</option>
<option value="DPDP">DPDP</option>
<option value="DPM">DPM</option>
<option value="DPMD">DPMD</option>
<option value="DPMM">DPMM</option>
<option value="DPMP">DPMP</option>
<option value="DPPD">DPPD</option>
<option value="DPPM">DPPM</option>
<option value="DPPP">DPPP</option>
<option value="E">E</option>
<option value="E*">E*</option>
<option value="EA">EA</option>
<option value="EAA">EAA</option>
<option value="EAB">EAB</option>
<option value="EAC">EAC</option>
<option value="EAD">EAD</option>
<option value="EAE">EAE</option>
<option value="EB">EB</option>
<option value="EBA">EBA</option>
<option value="EBB">EBB</option>
<option value="EBC">EBC</option>
<option value="EBD">EBD</option>
<option value="EBE">EBE</option>
<option value="EC">EC</option>
<option value="ECA">ECA</option>
<option value="ECB">ECB</option>
<option value="ECC">ECC</option>
<option value="ECD">ECD</option>
<option value="ECE">ECE</option>
<option value="ED">ED</option>
<option value="EDA">EDA</option>
<option value="EDB">EDB</option>
<option value="EDC">EDC</option>
<option value="EDD">EDD</option>
<option value="EDE">EDE</option>
<option value="EE">EE</option>
<option value="EEA">EEA</option>
<option value="EEB">EEB</option>
<option value="EEC">EEC</option>
<option value="EED">EED</option>
<option value="EEE">EEE</option>
<option value="EF">EF</option>
<option value="EG">EG</option>
<option value="F">F</option>
<option value="F*">F*</option>
<option value="FA">FA</option>
<option value="FL">Fail</option>
<option value="FB">FB</option>
<option value="FC">FC</option>
<option value="FD">FD</option>
<option value="FE">FE</option>
<option value="FF">FF</option>
<option value="FG">FG</option>
<option value="FI">First class honours</option>
<option value="FO">Fourth class honours</option>
<option value="G">G</option>
<option value="G*">G*</option>
<option value="GA">GA</option>
<option value="GB">GB</option>
<option value="GC">GC</option>
<option value="GD">GD</option>
<option value="GE">GE</option>
<option value="GN">General</option>
<option value="GF">GF</option>
<option value="GG">GG</option>
<option value="SL">Lower second class honours</option>
<option value="M1">M1</option>
<option value="M2">M2</option>
<option value="M3">M3</option>
<option value="MDD">MDD</option>
<option value="MDDD">MDDD</option>
<option value="MDDM">MDDM</option>
<option value="MDDP">MDDP</option>
<option value="MDM">MDM</option>
<option value="MDMD">MDMD</option>
<option value="MDMM">MDMM</option>
<option value="MDMP">MDMP</option>
<option value="MDP">MDP</option>
<option value="MDPD">MDPD</option>
<option value="MDPM">MDPM</option>
<option value="MDPP">MDPP</option>
<option value="ME">Merit</option>
<option value="MD">Merit Distinction</option>
<option value="MM">MERIT MERIT</option>
<option value="MMM">MERIT MERIT MERIT</option>
<option value="MMP">MERIT MERIT PASS</option>
<option value="MP">MERIT PASS</option>
<option value="MPP">MERIT PASS PASS</option>
<option value="MMD">MMD</option>
<option value="MMDD">MMDD</option>
<option value="MMDM">MMDM</option>
<option value="MMDP">MMDP</option>
<option value="MMMD">MMMD</option>
<option value="MMMM">MMMM</option>
<option value="MMMP">MMMP</option>
<option value="MMPD">MMPD</option>
<option value="MMPM">MMPM</option>
<option value="MMPP">MMPP</option>
<option value="MPD">MPD</option>
<option value="MPDD">MPDD</option>
<option value="MPDM">MPDM</option>
<option value="MPDP">MPDP</option>
<option value="MPM">MPM</option>
<option value="MPMD">MPMD</option>
<option value="MPMM">MPMM</option>
<option value="MPMP">MPMP</option>
<option value="MPPD">MPPD</option>
<option value="MPPM">MPPM</option>
<option value="MPPP">MPPP</option>
<option value="N">N</option>
<option value="E1">need at entry 1</option>
<option value="E2">need at entry 2</option>
<option value="NK">Not known</option>
<option value="OR">Ordinary</option>
<option value="OTH">Other grade not included on the list above</option>
<option value="PA">Pass</option>
<option value="PD">Pass Distinction</option>
<option value="PDD">Pass Distinction Distinction</option>
<option value="PDM">Pass Distinction Merit</option>
<option value="PDP">Pass Distinction Pass</option>
<option value="PM">Pass Merit</option>
<option value="PMD">Pass Merit Distinction</option>
<option value="PMM">Pass Merit Merit</option>
<option value="PMP">Pass Merit Pass</option>
<option value="PP">PASS PASS</option>
<option value="PPD">Pass Pass Distinction</option>
<option value="PPM">Pass Pass Merit</option>
<option value="PPP">PASS PASS PASS</option>
<option value="PDDD">PDDD</option>
<option value="PDDM">PDDM</option>
<option value="PDDP">PDDP</option>
<option value="PDMD">PDMD</option>
<option value="PDMM">PDMM</option>
<option value="PDMP">PDMP</option>
<option value="PDPD">PDPD</option>
<option value="PDPM">PDPM</option>
<option value="PDPP">PDPP</option>
<option value="01">Percentage mark 01</option>
<option value="02">Percentage mark 02</option>
<option value="03">Percentage mark 03</option>
<option value="04">Percentage mark 04</option>
<option value="05">Percentage mark 05</option>
<option value="06">Percentage mark 06</option>
<option value="07">Percentage mark 07</option>
<option value="08">Percentage mark 08</option>
<option value="09">Percentage mark 09</option>
<option value="10">Percentage mark 10</option>
<option value="11">Percentage mark 11</option>
<option value="12">Percentage mark 12</option>
<option value="13">Percentage mark 13</option>
<option value="14">Percentage mark 14</option>
<option value="15">Percentage mark 15</option>
<option value="16">Percentage mark 16</option>
<option value="17">Percentage mark 17</option>
<option value="18">Percentage mark 18</option>
<option value="19">Percentage mark 19</option>
<option value="20">Percentage mark 20</option>
<option value="21">Percentage mark 21</option>
<option value="22">Percentage mark 22</option>
<option value="23">Percentage mark 23</option>
<option value="24">Percentage mark 24</option>
<option value="25">Percentage mark 25</option>
<option value="26">Percentage mark 26</option>
<option value="27">Percentage mark 27</option>
<option value="28">Percentage mark 28</option>
<option value="29">Percentage mark 29</option>
<option value="30">Percentage mark 30</option>
<option value="31">Percentage mark 31</option>
<option value="32">Percentage mark 32</option>
<option value="33">Percentage mark 33</option>
<option value="34">Percentage mark 34</option>
<option value="35">Percentage mark 35</option>
<option value="36">Percentage mark 36</option>
<option value="37">Percentage mark 37</option>
<option value="38">Percentage mark 38</option>
<option value="39">Percentage mark 39</option>
<option value="40">Percentage mark 40</option>
<option value="41">Percentage mark 41</option>
<option value="42">Percentage mark 42</option>
<option value="43">Percentage mark 43</option>
<option value="44">Percentage mark 44</option>
<option value="45">Percentage mark 45</option>
<option value="46">Percentage mark 46</option>
<option value="47">Percentage mark 47</option>
<option value="48">Percentage mark 48</option>
<option value="49">Percentage mark 49</option>
<option value="50">Percentage mark 50</option>
<option value="51">Percentage mark 51</option>
<option value="52">Percentage mark 52</option>
<option value="53">Percentage mark 53</option>
<option value="54">Percentage mark 54</option>
<option value="55">Percentage mark 55</option>
<option value="56">Percentage mark 56</option>
<option value="57">Percentage mark 57</option>
<option value="58">Percentage mark 58</option>
<option value="59">Percentage mark 59</option>
<option value="60">Percentage mark 60</option>
<option value="61">Percentage mark 61</option>
<option value="62">Percentage mark 62</option>
<option value="63">Percentage mark 63</option>
<option value="64">Percentage mark 64</option>
<option value="65">Percentage mark 65</option>
<option value="66">Percentage mark 66</option>
<option value="67">Percentage mark 67</option>
<option value="68">Percentage mark 68</option>
<option value="69">Percentage mark 69</option>
<option value="70">Percentage mark 70</option>
<option value="71">Percentage mark 71</option>
<option value="72">Percentage mark 72</option>
<option value="73">Percentage mark 73</option>
<option value="74">Percentage mark 74</option>
<option value="75">Percentage mark 75</option>
<option value="76">Percentage mark 76</option>
<option value="77">Percentage mark 77</option>
<option value="78">Percentage mark 78</option>
<option value="79">Percentage mark 79</option>
<option value="80">Percentage mark 80</option>
<option value="81">Percentage mark 81</option>
<option value="82">Percentage mark 82</option>
<option value="83">Percentage mark 83</option>
<option value="84">Percentage mark 84</option>
<option value="85">Percentage mark 85</option>
<option value="86">Percentage mark 86</option>
<option value="87">Percentage mark 87</option>
<option value="88">Percentage mark 88</option>
<option value="89">Percentage mark 89</option>
<option value="90">Percentage mark 90</option>
<option value="91">Percentage mark 91</option>
<option value="92">Percentage mark 92</option>
<option value="93">Percentage mark 93</option>
<option value="94">Percentage mark 94</option>
<option value="95">Percentage mark 95</option>
<option value="96">Percentage mark 96</option>
<option value="97">Percentage mark 97</option>
<option value="98">Percentage mark 98</option>
<option value="99">Percentage mark 99</option>
<option value="PMDD">PMDD</option>
<option value="PMDM">PMDM</option>
<option value="PMDP">PMDP</option>
<option value="PMMD">PMMD</option>
<option value="PMMM">PMMM</option>
<option value="PMMP">PMMP</option>
<option value="PMPD">PMPD</option>
<option value="PMPM">PMPM</option>
<option value="PMPP">PMPP</option>
<option value="PPDD">PPDD</option>
<option value="PPDM">PPDM</option>
<option value="PPDP">PPDP</option>
<option value="PPMD">PPMD</option>
<option value="PPMM">PPMM</option>
<option value="PPMP">PPMP</option>
<option value="PPPD">PPPD</option>
<option value="PPPM">PPPM</option>
<option value="PPPP">PPPP</option>
<option value="TH">Third class honours</option>
<option value="U">U</option>
<option value="UH">Unclassified honours</option>
<option value="SE">Undivided second class honours</option>
<option value="SU">Upper second class honours</option>
<option value="X">X</option>
<option value="Y">Y</option>