<option value="A2AN">A2 (Any Subject)</option>
<option value="ASAN">AS (Any Subject)</option>
<option value="BTCD">BTEC 90 Credit Level 3 (Any subject)</option>
<option value="BTA2">BTEC Award Level 2 (Any subject)</option>
<option value="BTC2">BTEC Certificate Level 2 (Any subject)</option>
<option value="BTC3">BTEC Certificate Level 3 (Any subject)</option>
<option value="BTD2">BTEC Diploma Level 2 (Any subject)</option>
<option value="BTED">BTEC Extended Diploma Level 3 (Any subject)</option>
<option value="GART">GCSE Art</option>
<option value="GBIO">GCSE Biology</option>
<option value="GBUS">GCSE Business</option>
<option value="GCHE">GCSE Chemistry</option>
	<option value="GDTE">GCSE Design and Technology</option>
<option value="GENG">GCSE English</option>
<option value="GELA">GCSE English Language</option>
<option value="GELI">GCSE English Literature</option>
<option value="GFRE">GCSE French</option>
<option value="GGEO">GCSE Geography</option>
<option value="GGER">GCSE German</option>
<option value="GHIS">GCSE History</option>
<option value="GHEC">GCSE Home Economics</option>
<option value="GHUM">GCSE Humanities</option>
<option value="GICT">GCSE ICT</option>
<option value="GMAT">GCSE Maths</option>
<option value="GMED">GCSE Media</option>
<option value="GPEE">GCSE PE</option>
<option value="GPHY">GCSE Physics</option>
<option value="GREL">GCSE RE</option>
<option value="GSCI">GCSE Science</option>
<option value="GSCD">GCSE Science (Double)</option>
<option value="GSPA">GCSE Spanish</option>